version: '3.8'

services:   
  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ../dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - microservices-network
      
  zipkin:
    image: openzipkin/zipkin:3.0.6
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://user:password@rabbitmq:5672
    networks:
      - microservices-network

     
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ../volume:/var/lib/postgresql/data
    networks:
      - microservices-network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
