filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*/*.log
  json.keys_under_root: true
  json.overwrite_keys: true  
  json.add_error_keys: true
  json.expand_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
