server:
  port: 8300
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/db-payment
    username: user
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always  
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
      
rabbitmq:
  exchange:
    paymentExchange: payments.v1.payment_created
    paymentMadeExchange: payments.v1.payment_made
  queue:
    paymentQueue: payments.v1.payment_created.send_payment
  key:
    paymentKey: payments.v1.payment_created.send_payment.key
    
jwt:
  expiration: 3600000
  refreshExpiration: 86400000
  public:
    key: 'classpath:app.pub'
    
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  tracing:
    sampling:
      probability: 1.0
      
logging:
  level:
    com:
      gustavo:
        paymentservice: DEBUG
