server:
  port: ${PORT}
  
spring:
  output:
    ansi:
      enabled: ALWAYS # Ativa a saida em cores ANSI.
  rabbitmq:
    host: ${PROD_AMQP_HOST}
    port: ${PROD_AMQP_PORT}
    username: ${PROD_AMQP_USERNAME}
    password: ${PROD_AMQP_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PROD_OAUTH_ISSUER_URI}
  cache:
    type: redis
    redis:
      key-prefix: "user-service::"
  data:
    redis:
      port: ${PROD_REDIS_PORT}
      host: ${PROD_REDIS_HOST}
  #zipkin:
    #base-url: http://localhost:9411 
    
resilience4j:
  circuitbreaker:
    instances:
      ticketsByUserCB:
      #https://resilience4j.readme.io/docs/circuitbreaker
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
                
      notificationsByUserCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

keycloak:
  server-url: ${PROD_KEYCLOAK_SERVER_URL}
  realm: ${PROD_KEYCLOAK_REALM}
  client-id: ${PROD_KEYCLOAK_CLIENT_ID}
  client-secret: ${PROD_KEYCLOAK_CLIENT_SECRET}
  username: ${PROD_KEYCLOAK_USERNAME}
  password: ${PROD_KEYCLOAK_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_DEFAULTZONE}

rabbitmq:
  exchange:
    userExchange: users.v1.user_event
  key:
    userKey: users.v1.user_event.send_user.key
    
springdoc:
  swagger-ui:
    oauth: 
      client-id: ${PROD_SWAGGER_OAUTH_CLIENT_ID}
      client-secret: ${PROD_SWAGGER_OAUTH_CLIENT_SECRET}
  show-actuator: true
   
management:
  zipkin:
    tracing:
      endpoint: ${PROD_ZIPKIN_TRACING_ENDPOINT}
  endpoints:
    web:
      exposure:
        include:
          - health
  tracing:
    sampling:
      probability: 0.05
  
logging:
  level:
    com:
      gustavo:
        userservice: DEBUG
    #root: DEBUG
