server:
  port: ${PORT:8888}
  
spring:
  application:
    name: config-server
  security:
    user:
      name: config
      password: password
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GustavoSC1/Event-Management-Distributed-System.git
          #username: username
          #password: password
          default-label: jwt
          search-paths: config-files/${GIT_SEARCH_PATHS:dev*}
