server:
  port: 8200
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
rabbitmq:
  exchange:
    notificationExchange:  notifications.v1.notification_created
    paymentMadeExchange: payments.v1.payment_made
  queue:
    notificationQueue: notifications.v1.notification_created.send_notification
    paymentMadeQueue: payments.v1.payment_made.send_confirmation_to_notification
  key:
    notificationKey: notifications.v1.notification_created.send_notification.key

