server:
  port: 8300
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: Always  
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
rabbitmq:
  exchange:
    paymentExchange: payments.v1.payment_created
    paymentMadeExchange: payments.v1.payment_made
  queue:
    paymentQueue: payments.v1.payment_created.send_payment
  key:
    paymentKey: payments.v1.payment_created.send_payment.key
    
jwt:
  expiration: 3600000
  refreshExpiration: 86400000
  public:
    key: 'classpath:app.pub'
    
management:
  endpoints:
    web:
      exposure:
        include:
          - health
  tracing:
    sampling:
      probability: 1.0
      
logging:
  level:
    com:
      gustavo:
        paymentservice: DEBUG
