server:
  port: 8100
  
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
rabbitmq:
  exchange:
    userExchange: users.v1.user_event
    notificationExchange:  notifications.v1.notification_created
  queue:
    userQueue: users.v1.user_event.send_user
  key:
    notificationKey: notifications.v1.notification_created.send_notification.key
    